name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t lika027_dockerimage
          docker tag lika027_dockerimage 244530008913.dkr.ecr.eu-west-1.amazonaws.com/lika027/lab5:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/lika027/lab5:$rev
          
          
  push_to_another_registry:
    name: Push Docker image to Docherhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build and push Docker image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build . -t cool_image
          docker tag cool_image lika027/cool_image$rev
          docker push lika027/cool_image$rev